### PR TITLE
OT Artifacts mapping and definitions

### PR DESCRIPTION
**Pull request by OG3x100**

### CODE REVIEW

**Comment by netfl0** [comment]
@OG3x100 I am seeing conflicts on this branch, can you resolve.

**Comment by OG3x100** [comment]
I don't have write access to src/ontology/initiatives/d3fend-ot-only.ttl

**Comment by netfl0** [comment]
I am seeing this error when i build this:

image


I think we need to merge develop into this branch as well.

**Comment by OG3x100** [comment]
I see you merged develop into the branch did that work?

**Pull request merged**
